# Generated by Django 4.2.6 on 2023-10-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):#migration class extending the migration class

    initial = True#tells django that this is the 1st migration file here in this applications

    dependencies = [ 
    ]

    operations = [#operations that should be performed.
        migrations.CreateModel(# these are some built in operations that are performed here that creates a table
            name='Book',#the created table name will be  Book
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
